- hosts: vms
  remote_user: root
  tasks:
    - name: update and install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes
    - name: add key repo
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
        filename: docker
    - name: install docker-ce
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
    - name: make sure docker is running
      ansible.builtin.service:
        name: docker
        state: started

